# Generated by Django 4.1 on 2022-08-28 14:59

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "unique_together": {("slug", "user")},
            },
        ),
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=300,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                ("subtitle", models.TextField(blank=True, null=True)),
                ("slug", models.SlugField(max_length=200)),
                ("link", models.URLField()),
                ("url", models.URLField(unique=True)),
                ("etag", models.CharField(blank=True, max_length=200, null=True)),
                ("last_modified", models.DateTimeField(null=True)),
                ("last_checked", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("favicon", models.ImageField(blank=True, null=True, upload_to="")),
                ("ttl", models.IntegerField(default=3600)),
            ],
            options={
                "ordering": ["title", "-last_modified"],
            },
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=400,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                ("link", models.URLField(blank=True, max_length=1000, null=True)),
                ("published", models.DateTimeField(null=True)),
                ("updated", models.DateTimeField(null=True)),
                ("slug", models.SlugField(max_length=400)),
                ("content", models.TextField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("guid", models.CharField(blank=True, max_length=400, null=True)),
                ("author", models.CharField(blank=True, max_length=400, null=True)),
                ("thumbnail", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="feeds.feed",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "entries",
                "ordering": ["-published", "title"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="feeds.category",
                    ),
                ),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="feeds.feed",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("feed", "user")},
            },
        ),
    ]
