# Generated by Django 4.1 on 2022-08-05 19:07

from django.db import migrations
from django.contrib.sites.models import Site


def create_site(apps, schema_editor):
    site = Site.objects.first()
    site.name = "localhost"
    site.domain = "http://localhost:8000"
    site.save()


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0001_initial"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [migrations.RunPython(create_site)]
