# Generated by Django 4.1 on 2022-08-05 19:07

from django.conf import settings
from django.contrib.sites.models import Site
from django.db import migrations


def create_site(apps, schema_editor):
    if settings.DEBUG:
        Site.objects.create(name="localhost", domain="http://localhost:8000")


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0001_initial"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [migrations.RunPython(create_site)]
