# Generated by Django 4.0.6 on 2022-07-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="entry",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="entry",
            name="guid",
            field=models.CharField(blank=True, max_length=400, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="entry",
            name="link",
            field=models.URLField(unique=True),
        ),
    ]
