# Generated by Django 4.1 on 2022-08-12 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0002_auto_20220805_1907"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="entry",
            name="duplicate link",
        ),
    ]
