# Generated by Django 4.1.1 on 2022-09-16 14:26

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0003_alter_feed_ttl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="ttl",
            field=models.DurationField(default=datetime.time(1, 0)),
        ),
    ]
