# Generated by Django 4.1 on 2022-08-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0003_remove_entry_duplicate link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="link",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
