# Generated by Django 4.0.6 on 2022-07-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0003_alter_entry_slug_alter_entry_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="link",
            field=models.URLField(max_length=300, unique=True),
        ),
    ]
