# Generated by Django 4.0.6 on 2022-07-14 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0004_alter_entry_link"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="entry",
            unique_together={("feed", "slug")},
        ),
    ]
