# Generated by Django 4.2rc1 on 2023-03-21 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0004_alter_feed_ttl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="ttl",
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
