# Generated by Django 4.1 on 2022-08-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0006_alter_entry_link"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="entry",
            name="duplicate guid",
        ),
        migrations.RemoveIndex(
            model_name="entry",
            name="feeds_entry_guid_bacd74_idx",
        ),
        migrations.AlterField(
            model_name="entry",
            name="guid",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
