# Generated by Django 4.1 on 2022-08-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0007_remove_entry_duplicate guid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="favicon",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
    ]
