# Generated by Django 4.0.6 on 2022-07-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0007_alter_entry_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="thumbnail",
            field=models.URLField(blank=True, null=True),
        ),
    ]
