# Generated by Django 4.1 on 2022-08-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0008_feed_favicon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="favicon",
            field=models.URLField(blank=True, null=True),
        ),
    ]
