# Generated by Django 4.0.6 on 2022-07-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0008_entry_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="thumbnail",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
