# Generated by Django 4.0.6 on 2022-07-24 21:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0009_alter_entry_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
