# Generated by Django 4.1 on 2022-08-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0009_alter_feed_favicon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="favicon",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
