# Generated by Django 4.1 on 2022-08-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0011_alter_feed_favicon"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="ttl",
            field=models.IntegerField(default=3600),
        ),
    ]
