# Generated by Django 4.0.6 on 2022-07-24 21:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0011_auto_20220724_2135"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
