# Generated by Django 4.0.6 on 2022-07-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0012_auto_20220724_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
