# Generated by Django 4.0.6 on 2022-07-30 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0014_alter_entry_unique_together_entry_duplicate guid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="title",
            field=models.CharField(
                max_length=300,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="feed",
            name="title",
            field=models.CharField(
                max_length=300,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
    ]
