# Generated by Django 4.0.6 on 2022-07-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0015_alter_entry_title_alter_feed_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="subtitle",
            field=models.TextField(blank=True, null=True),
        ),
    ]
