# Generated by Django 4.0.6 on 2022-07-30 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0016_alter_feed_subtitle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="title",
            field=models.CharField(
                max_length=400,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
    ]
