# Generated by Django 4.0.6 on 2022-07-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0017_alter_entry_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="slug",
            field=models.SlugField(max_length=400),
        ),
    ]
